### ISSUE TITLE
Process api - FD resolver

### ISSUE THREAD

**Issue by Thoronir42** [vairad/zcu-os#27]
Add function for
- setting vfs file descriptor to process fd table, which returns linear fd Thandle

**Comment by vairad** [comment]
prototypes:
  -  `THandle process::getSystemFD(const Thandle program_handle)` 
  -  `THandle process::setNewFD(const Thandle system_handle)` 

will be avaliable in process_api.h

**Comment by vairad** [comment]
Merged to master
