### ISSUE TITLE
Test cd

### ISSUE THREAD

**Issue by buzzcz** [vairad/zcu-os#53]
- Test relative paths without "." and ".."
- Test "." and ".."
- Test relative paths with "." and ".."
- Test absolute paths with "C:/" and "C:/some/path"
- Test with backslashes in paths
- Test relative path with "C:/"

**Comment by Thoronir42** [comment]
Most of the test cases are now passing.
![image](https://user-images.githubusercontent.com/11042105/33606887-60af7840-d9bf-11e7-8dd6-71112b94620c.png)

I did not understand the last case, would you care to elaborate? ⭕️_⭕️

**Comment by buzzcz** [comment]
I was thinking something like "C:/comics/marvel/../marvel/.." but it seems to work great :)
