### ISSUE TITLE
Prompt in subdirectory is wrong

### ISSUE THREAD

**Issue by buzzcz** [vairad/zcu-os#54]
What I did:
- md test
- cd test
    - I got: "C:/test>" as prompt
- md final
- cd final
    - I got: "C:/testfinal>" as prompt

**Comment by Thoronir42** [comment]
Please include a "What I had:" describing context is possible. In this case you'd possibly be in initial state looking at prompt `C:/>`

CD result is inconsistent with the state 0 as it leaves you in `c:/test>`, missing the final backslash

**Comment by Thoronir42** [comment]
I just checked the windows cmd and apparently that's the way it's supposed to be.

In this case the fix is to edit `vfs_paths::normalizePath()` function to add trailing slash after initializing absolute path with current working directory.

**Comment by Thoronir42** [comment]
Fixed
![image](https://user-images.githubusercontent.com/11042105/33603370-949c342a-d9b2-11e7-9d15-d6fb92de0ca9.png)
