### ISSUE TITLE
md - recursive

### ISSUE THREAD

**Issue by buzzcz** [vairad/zcu-os#55]
What I did:
- md test/final
- cd test
- cd final
    - I got: "System could not find selected path" error

What I did:
- md test/final
- cd test/final
    - Works ok, I got prompt "C:/test/final"

**Comment by Thoronir42** [comment]
Most likely related to #54 as changing directory to test leaves working directory at "C:/test"

**Comment by Thoronir42** [comment]
Fixed along with #54
