### ISSUE TITLE
GetWD in common results in crash

### ISSUE THREAD

**Issue by Thoronir42** [vairad/zcu-os#57]
The getWD function sometimes crashes on [read byte count validation](https://github.com/vairad/zcu-os/blob/f8aa631a1eba9174c2fab576c5e2cc728e05ec96/src/user/common.cpp#L114).

Steps to reproduce:

1. Start up
2. `md a/b/c`
3. `cd a/b/c`

**Comment by vairad** [comment]
O:) ... sizeof bug ...
