### ISSUE TITLE
Provided api.h contains mismatched syscall values

### ISSUE THREAD

**Issue by Thoronir42** [vairad/zcu-os#6]
The [documentation comment](https://github.com/vairad/zcu-os/blob/master/src/api/api.h#L80-L99) does not correspond to the [updated syscall values](https://github.com/vairad/zcu-os/blob/master/src/api/api.h#L141-L147).

**Comment by Thoronir42** [comment]
The docummented values have been aligned for now, updated api.h containing the new syscall is yet to be provided.

**Comment by buzzcz** [comment]
Although it's a bit different bug, api.h still contains renamed streams. It should be changed back to the original ones.
