### ISSUE TITLE
Create program "md"

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-os#8]
Make directory:

Creates a directory.

MKDIR [drive:]path
MD [drive:]path

If Command Extensions are enabled MKDIR changes as follows:

MKDIR creates any intermediate directories in the path, if needed.
For example, assume \a does not exist then:

    mkdir \a\b\c\d

is the same as:

    mkdir \a
    chdir \a
    mkdir b
    chdir b
    mkdir c
    chdir c
    mkdir d

which is what you would have to type if extensions were disabled.

**Comment by buzzcz** [comment]
@Thoronir42 We need to specify in documentation if this and similar programs use these so called extensions or if each directory in this case needs to be created separately.

**Comment by vairad** [comment]
Tested to VFS interface.

**Comment by Thoronir42** [comment]
If during file opening a flag `kiv_os::fmOpen_Always` is not set, a whole directory structure is ensured to exist up to the desired file, provided that one of the path parts is not an existing non-directory file.

**Comment by Thoronir42** [comment]
![image](https://user-images.githubusercontent.com/11042105/33607804-9d2c430e-d9c2-11e7-8b40-7a8b06173fb0.png)
