### ISSUE TITLE
Create program "rd"

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-os#9]
Remove directory:
Removes (deletes) a directory.

RMDIR [/S] [/Q] [drive:]path
RD [/S] [/Q] [drive:]path

    /S      Removes all directories and files in the specified directory
            in addition to the directory itself.  Used to remove a directory
            tree.

    /Q      Quiet mode, do not ask if ok to remove a directory tree with /S

**Comment by Thoronir42** [comment]
When deleting a directory, there is no straightforward way to pass these parameters (as far as the current api.h goes) so when deleting a directory, it and all of its children are deleted

**Comment by buzzcz** [comment]
Also deletes files
